# Generated by Django 4.2.13 on 2024-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_subtitle', models.CharField(max_length=200)),
                ('article_description', models.TextField()),
                ('article_day_posted', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
