# Generated by Django 4.2.13 on 2024-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_delete_cars_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('health', 'Health'), ('mindset', 'Mindset')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
