# Generated by Django 4.2.13 on 2024-07-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_client_user_user_password_alter_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='WeightGraphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_day', models.DateTimeField(auto_now_add=True)),
                ('updated_day', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graphic', to='myapp.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
