# Generated by Django 4.2.13 on 2024-07-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_client_client_email_weightgraphic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightgraphic',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='myapp.client'),
        ),
    ]
