# Generated by Django 4.2.13 on 2024-07-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_weightgraphic_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightgraphic',
            name='month',
        ),
        migrations.RemoveField(
            model_name='weightgraphic',
            name='updated_day',
        ),
        migrations.RemoveField(
            model_name='weightgraphic',
            name='year',
        ),
    ]
