# Generated by Django 4.2.13 on 2024-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('day_posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('health', 'Health'), ('mindset', 'Mindset')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['-day_posted'],
                'indexes': [models.Index(fields=['-day_posted'], name='blog_post_day_pos_35d841_idx')],
            },
        ),
    ]
